### ISSUE TITLE
/exist/xmlrpc: An unknown error occurred: GC overhead limit exceeded - Errors observed for ExistDB  and Exist DB is getting corrupted on regular basis

### ISSUE THREAD

**Issue by sbhusala** [eXist-db/exist#2754]
### What is the problem
/exist/xmlrpc: An unknown error occurred: GC overhead limit exceeded - Errors observed for ExistDB and Exist DB is getting corrupted on regular basis

### What did you expect
> Describe what you expected to happen. Add for example a reference to a [specification](https://www.w3.org/TR/xquery-3/).

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 
- Java version (e.g. Java8u121)
- Operating system (Windows 7, Linux, MacOs)
- 32 or 64 bit
- How is eXist-db installed? (JAR installer, DMG, WAR file, clone from GitHub)
- Any custom changes in e.g. conf.xml
![image](https://user-images.githubusercontent.com/46970364/58419423-de019a80-808a-11e9-9f78-4c62314ea970.png)

**Comment by adamretter** [comment]
Hey @sbhusala this is a memory related problem. Many memory issues have been fixed since eXist-db 3.0.0, could you please try 4.7.0?

**Comment by dizzzz** [comment]
additionally, you could try to switch on the G1 garbage collector. but v4.7 is for sure the best step.

**Comment by adamretter** [comment]
Closing due to inactivity.

**Comment by sbhusala** [comment]
Dear All,

We have upgraded to 4.7 eXst db version, however we are still receiving  GC overhead limit exceeded  error. can you please suggest on next steps ?

**Comment by duncdrum** [comment]
Is there any steps that you can take to reproduce this? If the error occurs on exist v5 please include new info on java version install method and conf.xml changes etc

**Comment by sbhusala** [comment]
Hi Duncan,

Replication of issue cannot be feasible manually , however it might be because of heavy load ? ( suspect).

java :
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

project.version=4.7.0
project.built=201905201236
scm.branch=refs/tags/eXist-4.7.0
scm.revision=64ba5134

**Comment by sbhusala** [comment]
[exist.log](https://github.com/eXist-db/exist/files/4067488/exist.log)
Attached logs as requeste
d.

**Comment by dizzzz** [comment]
for me, in some cases enabling the G1C garbage collector helped a lot....

**Comment by line-o** [comment]
Propose to close this issue without further action.
